#!/bin/sh

touch $1

ext=${1##*.}

if [ ! -s $1 ]; then
	echo "/**" >> $1
	echo " *     author:   matcha1024" >> $1
	echo " *     created:  `date`" >> $1
	echo "**/" >> $1
	if [ $ext = "cpp" ]; then
	echo "" >> $1
	echo "#include<bits/stdc++.h>" >> $1
	echo "using namespace std;" >> $1
	echo "typedef long long ll;" >> $1
	echo "typedef pair<int, int> P;" >> $1
	echo "#define forin(in) for(int i=0; i<(int)in.size(); i++) cin>>in[i]" >> $1
	echo "#define forout(out) for(int i=0; i<(int)out.size(); i++) cout<<out[i]<<endl" >> $1
	echo "#define rep(i, n) for(int i=0; i<(n); i++)" >> $1
	echo "template<class T> inline bool chmax(T& a, T b) { if (a < b) { a = b; return 1; } return 0; }" >> $1
	echo "template<class T> inline bool chmin(T& a, T b) { if (a > b) { a = b; return 1; } return 0; }" >> $1
	echo "const int INF = 1e9;" >> $1
	echo "" >> $1
	echo "int main(){" >> $1
	echo "	" >> $1
	echo "	return 0;" >> $1
	echo "}" >> $1
	fi
fi
subl.exe $1